// <auto-generated />
using ExercicioManipulacaoDb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExercicioManipulacaoDb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExercicioManipulacaoDb.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LaunchingYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LaunchingYear = "2022",
                            Name = "NieR: Replicant",
                            Price = 249.90000000000001
                        },
                        new
                        {
                            Id = 2,
                            LaunchingYear = "2025",
                            Name = "The Elder Scrolls IV: Oblivion Remastered",
                            Price = 264.89999999999998
                        },
                        new
                        {
                            Id = 3,
                            LaunchingYear = "2021",
                            Name = "Elden Ring",
                            Price = 274.5
                        });
                });

            modelBuilder.Entity("ExercicioManipulacaoDb.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Franz Liszt",
                            Genre = "Classical",
                            Name = "Liebestraume no. 3"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Ella Fitzgerald",
                            Genre = "Jazz",
                            Name = "Tea For Two"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Fat Family",
                            Genre = "R&B",
                            Name = "Madrugada"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
